#!/bin/sh

# example: ./gitPullPush samalws.com-3 github master samalws

cd ~

~/cmds/initRepo $1 ${4:-samalws}
cd $1.git

~/cmds/barePull ${2:-github} ${3:-master}
git push ${2:-github} ${3:-master}
